class_name Modifiers

enum Rarity {
  COMMON,
  RARE,
  LEGENDARY
}

enum Effect {
  FREEZE,
  MARK,
  STUN,
  BURN,
  INTOXICATE,
  REACT,
  UNSTACK,
  STACK,
  LEECH,
  RETURN,
  IMPACT
}

enum Gun {
  NONE,
  HOMING,
  LIGHTNING,
  QUICK_RELOAD,
  LARGE_MAGAZINE,
  BOTTOMLESS_MAGAZINE,
  SCATTERSHOT,
  CHAIN,
  LASER,
  EXPLOSIVE,
  SPEEDY,
  RAPID_FIRE,
  ONE_HIT_WONDER,
  LONG_RANGE,
  PIERCING,
  RADIAL,
  VAMPIRIC,
  FREEZING,
  MARKING,
  TRICK_SHOT,
  ASSASSIN,
  STACKING,
  IMPACT,
  LUCKY,
  STUNNING,
  HOT_SHOT,
  INTOXICATING,
  FRONT_LOADED,
  POWERFUL,
  REACTIVE,
  BLAZE_OF_GLORY,
  BULLET_EATER,
  RICOCHET,
  GROWING,
  BIG_SHOT,
  RETURNING
}

const DESCRIPTIONS: Dictionary = {
  Gun.NONE: "Well that isn't very exciting...",
  Gun.HOMING: "This one doesn't work yet",
  Gun.LIGHTNING: "This one doesn't work yet",
  Gun.QUICK_RELOAD: "+100% reload speed",
  Gun.LARGE_MAGAZINE: "+100% magazine size",
  Gun.BOTTOMLESS_MAGAZINE: "Never reload again!",
  Gun.SCATTERSHOT: "Fire a spread of weaker bolts",
  Gun.CHAIN: "This one doesn't work yet",
  Gun.LASER: "This one doesn't work yet",
  Gun.EXPLOSIVE: "This one doesn't work yet",
  Gun.SPEEDY: "Spells travel twice as fast",
  Gun.RAPID_FIRE: "+100% fire rate",
  Gun.ONE_HIT_WONDER: "Fire your entire magazine in one shot for half damage!",
  Gun.LONG_RANGE: "This one doesn't work yet",
  Gun.PIERCING: "Spells pierce through an additional enemy",
  Gun.RADIAL: "Fire bullets all around you",
  Gun.VAMPIRIC: "Dealing damage has a chance to heal you",
  Gun.FREEZING: "Slows enemies",
  Gun.MARKING: "Double damage, but the damage doesn't occur until a second gun shoots them",
  Gun.TRICK_SHOT: "This one doesn't work yet",
  Gun.ASSASSIN: "This one doesn't work yet",
  Gun.STACKING: "This one doesn't work yet",
  Gun.IMPACT: "This one doesn't work yet",
  Gun.LUCKY: "This one doesn't work yet",
  Gun.STUNNING: "Dealing damage has a chance to stun enemies",
  Gun.HOT_SHOT: "May cause the target to catch on fire",
  Gun.INTOXICATING: "This one doesn't work yet",
  Gun.FRONT_LOADED: "Double damage, but enemies build tolerance to your shots",
  Gun.POWERFUL: "Twice the damage, but half the speed",
  Gun.REACTIVE: "Deal extra damage for every status effect on an enemy",
  Gun.BLAZE_OF_GLORY: "Deal triple damage if below 30% health",
  Gun.BULLET_EATER: "This one doesn't work yet",
  Gun.RICOCHET: "Spells bounce off a wall an additional time",
  Gun.GROWING: "This one doesn't work yet",
  Gun.BIG_SHOT: "Larger spells",
  Gun.RETURNING: "Hitting an enemy loads a spell into your magazine"
}

const NAMES: Dictionary = {
  Gun.NONE: "Empty",
  Gun.HOMING: "Homing",
  Gun.LIGHTNING: "Lightning",
  Gun.QUICK_RELOAD: "Quick Reload",
  Gun.LARGE_MAGAZINE: "Large Magazine",
  Gun.BOTTOMLESS_MAGAZINE: "Bottomless Magazine",
  Gun.SCATTERSHOT: "Scattershot",
  Gun.CHAIN: "Chain",
  Gun.LASER: "Laser",
  Gun.EXPLOSIVE: "Explosive",
  Gun.SPEEDY: "Speedy",
  Gun.RAPID_FIRE: "Rapid Fire",
  Gun.ONE_HIT_WONDER: "One Hit Wonder",
  Gun.LONG_RANGE: "Long Range",
  Gun.PIERCING: "Piercing",
  Gun.RADIAL: "Radial",
  Gun.VAMPIRIC: "Vampiric",
  Gun.FREEZING: "Freezing",
  Gun.MARKING: "Marking",
  Gun.TRICK_SHOT: "Trick Shot",
  Gun.ASSASSIN: "Assassin",
  Gun.STACKING: "Stacking",
  Gun.IMPACT: "Impact",
  Gun.LUCKY: "Lucky",
  Gun.STUNNING: "Stunning",
  Gun.HOT_SHOT: "Hot Shot",
  Gun.INTOXICATING: "Intoxicating",
  Gun.FRONT_LOADED: "Front Loaded",
  Gun.POWERFUL: "Powerful",
  Gun.REACTIVE: "Reactive",
  Gun.BLAZE_OF_GLORY: "Blaze of Glory",
  Gun.BULLET_EATER: "Bullet Eater",
  Gun.RICOCHET: "Ricochet",
  Gun.GROWING: "Growing",
  Gun.BIG_SHOT: "Big Shot",
  Gun.RETURNING: "Returning"
}

const RARITIES: Dictionary = {
  Gun.NONE: Rarity.COMMON,
  Gun.HOMING: Rarity.COMMON,
  Gun.LIGHTNING: Rarity.COMMON,
  Gun.QUICK_RELOAD: Rarity.COMMON,
  Gun.LARGE_MAGAZINE: Rarity.COMMON,
  Gun.BOTTOMLESS_MAGAZINE: Rarity.COMMON,
  Gun.SCATTERSHOT: Rarity.COMMON,
  Gun.CHAIN: Rarity.COMMON,
  Gun.LASER: Rarity.COMMON,
  Gun.EXPLOSIVE: Rarity.COMMON,
  Gun.SPEEDY: Rarity.COMMON,
  Gun.RAPID_FIRE: Rarity.COMMON,
  Gun.ONE_HIT_WONDER: Rarity.COMMON,
  Gun.LONG_RANGE: Rarity.COMMON,
  Gun.PIERCING: Rarity.COMMON,
  Gun.RADIAL: Rarity.COMMON,
  Gun.VAMPIRIC: Rarity.COMMON,
  Gun.FREEZING: Rarity.COMMON,
  Gun.MARKING: Rarity.COMMON,
  Gun.TRICK_SHOT: Rarity.COMMON,
  Gun.ASSASSIN: Rarity.COMMON,
  Gun.STACKING: Rarity.COMMON,
  Gun.IMPACT: Rarity.COMMON,
  Gun.LUCKY: Rarity.COMMON,
  Gun.STUNNING: Rarity.COMMON,
  Gun.HOT_SHOT: Rarity.COMMON,
  Gun.INTOXICATING: Rarity.COMMON,
  Gun.FRONT_LOADED: Rarity.COMMON,
  Gun.POWERFUL: Rarity.COMMON,
  Gun.REACTIVE: Rarity.COMMON,
  Gun.BLAZE_OF_GLORY: Rarity.COMMON,
  Gun.BULLET_EATER: Rarity.COMMON,
  Gun.RICOCHET: Rarity.COMMON,
  Gun.GROWING: Rarity.COMMON,
  Gun.BIG_SHOT: Rarity.COMMON,
  Gun.RETURNING: Rarity.COMMON
}
